// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TabuKA.Data;

#nullable disable

namespace TabuKA.Migrations
{
    [DbContext(typeof(TabuKADbContext))]
    [Migration("20260919232128_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.12");

            modelBuilder.Entity("TabuKA.Entities.AppSettings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.ToTable("AppSettings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 9, 19, 23, 21, 27, 680, DateTimeKind.Utc).AddTicks(2672),
                            Description = "Uygulama teması (Light/Dark/System)",
                            Key = "Theme",
                            Type = 0,
                            Value = "System"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 9, 19, 23, 21, 27, 680, DateTimeKind.Utc).AddTicks(4400),
                            Description = "Uygulama dili",
                            Key = "Language",
                            Type = 0,
                            Value = "tr-TR"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 9, 19, 23, 21, 27, 680, DateTimeKind.Utc).AddTicks(4402),
                            Description = "Genel ses seviyesi (0-100)",
                            Key = "MasterVolume",
                            Type = 1,
                            Value = "80"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2026, 9, 19, 23, 21, 27, 680, DateTimeKind.Utc).AddTicks(4404),
                            Description = "Otomatik kaydetme aktif",
                            Key = "AutoSave",
                            Type = 2,
                            Value = "true"
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2026, 9, 19, 23, 21, 27, 680, DateTimeKind.Utc).AddTicks(4405),
                            Description = "İlk açılışta öğretici göster",
                            Key = "ShowTutorial",
                            Type = 2,
                            Value = "true"
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2026, 9, 19, 23, 21, 27, 680, DateTimeKind.Utc).AddTicks(4408),
                            Description = "Veritabanı şema sürümü",
                            Key = "DatabaseVersion",
                            Type = 1,
                            Value = "1"
                        });
                });

            modelBuilder.Entity("TabuKA.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 9, 19, 23, 21, 27, 678, DateTimeKind.Utc).AddTicks(1496),
                            Description = "Genel kelimeler",
                            IsActive = true,
                            Name = "Genel",
                            SortOrder = 1
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 9, 19, 23, 21, 27, 678, DateTimeKind.Utc).AddTicks(3506),
                            Description = "Hayvanlarla ilgili kelimeler",
                            IsActive = true,
                            Name = "Hayvanlar",
                            SortOrder = 2
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 9, 19, 23, 21, 27, 678, DateTimeKind.Utc).AddTicks(3510),
                            Description = "Yiyecek ve içeceklerle ilgili kelimeler",
                            IsActive = true,
                            Name = "Yiyecekler",
                            SortOrder = 3
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2026, 9, 19, 23, 21, 27, 678, DateTimeKind.Utc).AddTicks(3512),
                            Description = "Günlük eşyalar",
                            IsActive = true,
                            Name = "Eşyalar",
                            SortOrder = 4
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2026, 9, 19, 23, 21, 27, 678, DateTimeKind.Utc).AddTicks(3514),
                            Description = "Meslek ve işlerle ilgili kelimeler",
                            IsActive = true,
                            Name = "Meslekler",
                            SortOrder = 5
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2026, 9, 19, 23, 21, 27, 678, DateTimeKind.Utc).AddTicks(3523),
                            Description = "Yer ve mekanlarla ilgili kelimeler",
                            IsActive = true,
                            Name = "Yerler",
                            SortOrder = 6
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2026, 9, 19, 23, 21, 27, 678, DateTimeKind.Utc).AddTicks(3524),
                            Description = "Fiiller ve eylemler",
                            IsActive = true,
                            Name = "Eylemler",
                            SortOrder = 7
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2026, 9, 19, 23, 21, 27, 678, DateTimeKind.Utc).AddTicks(3526),
                            Description = "Doğa olayları ve öğeleri",
                            IsActive = true,
                            Name = "Doğa",
                            SortOrder = 8
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(2026, 9, 19, 23, 21, 27, 678, DateTimeKind.Utc).AddTicks(3527),
                            Description = "Teknoloji ve bilgisayar terimleri",
                            IsActive = true,
                            Name = "Teknoloji",
                            SortOrder = 9
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(2026, 9, 19, 23, 21, 27, 678, DateTimeKind.Utc).AddTicks(3529),
                            Description = "Spor dalları ve terimleri",
                            IsActive = true,
                            Name = "Spor",
                            SortOrder = 10
                        });
                });

            modelBuilder.Entity("TabuKA.Entities.GameSession", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CurrentRound")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CurrentTeamIndex")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("EndedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("GameDataJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("GameSettingsId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("TeamId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TotalRounds")
                        .HasColumnType("INTEGER");

                    b.Property<string>("WinnerTeamId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("GameSettingsId");

                    b.HasIndex("TeamId");

                    b.ToTable("GameSessions");
                });

            modelBuilder.Entity("TabuKA.Entities.GameSettings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("EnableAutoTabooCheck")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("EnableSound")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("PassLimit")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RoundTimeSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ScoreToWin")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SelectedCategoryIdsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TeamCount")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("UseCustomCategories")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Volume")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("GameSettings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 9, 19, 23, 21, 27, 679, DateTimeKind.Utc).AddTicks(2712),
                            EnableAutoTabooCheck = false,
                            EnableSound = true,
                            IsDefault = true,
                            Name = "Varsayılan",
                            PassLimit = 3,
                            RoundTimeSeconds = 60,
                            ScoreToWin = 0,
                            SelectedCategoryIdsJson = "[]",
                            TeamCount = 2,
                            UseCustomCategories = false,
                            Volume = 80
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 9, 19, 23, 21, 27, 679, DateTimeKind.Utc).AddTicks(6295),
                            EnableAutoTabooCheck = false,
                            EnableSound = true,
                            IsDefault = false,
                            Name = "Hızlı Oyun",
                            PassLimit = 1,
                            RoundTimeSeconds = 30,
                            ScoreToWin = 10,
                            SelectedCategoryIdsJson = "[]",
                            TeamCount = 2,
                            UseCustomCategories = false,
                            Volume = 80
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 9, 19, 23, 21, 27, 679, DateTimeKind.Utc).AddTicks(6299),
                            EnableAutoTabooCheck = false,
                            EnableSound = true,
                            IsDefault = false,
                            Name = "Uzun Oyun",
                            PassLimit = 5,
                            RoundTimeSeconds = 90,
                            ScoreToWin = 25,
                            SelectedCategoryIdsJson = "[]",
                            TeamCount = 2,
                            UseCustomCategories = false,
                            Volume = 80
                        });
                });

            modelBuilder.Entity("TabuKA.Entities.Player", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TeamId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("TeamId");

                    b.ToTable("Players");
                });

            modelBuilder.Entity("TabuKA.Entities.Round", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("EndedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("GameSessionId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<int>("PassUsed")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Result")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RoundNumber")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ScoreGained")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("TeamId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TimeUsedSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<int>("WordId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("GameSessionId");

                    b.HasIndex("TeamId");

                    b.HasIndex("WordId");

                    b.ToTable("Rounds");
                });

            modelBuilder.Entity("TabuKA.Entities.Team", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("CurrentRound")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("PassUsed")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Score")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Teams");
                });

            modelBuilder.Entity("TabuKA.Entities.Word", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Difficulty")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ForbiddenWordsJson")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MainWord")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("MainWord", "CategoryId")
                        .IsUnique();

                    b.ToTable("Words");
                });

            modelBuilder.Entity("TabuKA.Entities.GameSession", b =>
                {
                    b.HasOne("TabuKA.Entities.GameSettings", "GameSettings")
                        .WithMany()
                        .HasForeignKey("GameSettingsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TabuKA.Entities.Team", null)
                        .WithMany("GameSessions")
                        .HasForeignKey("TeamId");

                    b.Navigation("GameSettings");
                });

            modelBuilder.Entity("TabuKA.Entities.Player", b =>
                {
                    b.HasOne("TabuKA.Entities.Team", "Team")
                        .WithMany("Players")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Team");
                });

            modelBuilder.Entity("TabuKA.Entities.Round", b =>
                {
                    b.HasOne("TabuKA.Entities.GameSession", "GameSession")
                        .WithMany("Rounds")
                        .HasForeignKey("GameSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TabuKA.Entities.Team", "Team")
                        .WithMany()
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TabuKA.Entities.Word", "Word")
                        .WithMany()
                        .HasForeignKey("WordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GameSession");

                    b.Navigation("Team");

                    b.Navigation("Word");
                });

            modelBuilder.Entity("TabuKA.Entities.Word", b =>
                {
                    b.HasOne("TabuKA.Entities.Category", "Category")
                        .WithMany("Words")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("TabuKA.Entities.Category", b =>
                {
                    b.Navigation("Words");
                });

            modelBuilder.Entity("TabuKA.Entities.GameSession", b =>
                {
                    b.Navigation("Rounds");
                });

            modelBuilder.Entity("TabuKA.Entities.Team", b =>
                {
                    b.Navigation("GameSessions");

                    b.Navigation("Players");
                });
#pragma warning restore 612, 618
        }
    }
}
